In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [9]:


df = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E"],
    "dept": ["Sales", "Sales", "HR", "HR", "HR"],
    "salary": [90000, 70000, 80000, 60000, 50000]
})
df
df["avg_salary"] = df.groupby("dept")["salary"].transform("mean")
df
df["rank"] = df.groupby("dept")["salary"].rank(method="dense",ascending=False)
df

  name   dept  salary    avg_salary  rank
0    A  Sales   90000  80000.000000   1.0
1    B  Sales   70000  80000.000000   2.0
2    C     HR   80000  63333.333333   1.0
3    D     HR   60000  63333.333333   2.0
4    E     HR   50000  63333.333333   3.0

In [11]:
employee=df[df["salary"]>70000]
employee

  name   dept  salary    avg_salary  rank
0    A  Sales   90000  80000.000000   1.0
2    C     HR   80000  63333.333333   1.0

In [13]:
sales_employee = df[
    (df["dept"] == "Sales") &
    (df["salary"] > 70000)
]
sales_employee

  name   dept  salary  avg_salary  rank
0    A  Sales   90000     80000.0   1.0

In [19]:
sale_hr_result = df[
    ((df["dept"] == "Sales") | (df["dept"] == "HR")) &
    (df["salary"] > 70000)
]
sale_hr_result

sale_hr_result2=df[(df["dept"].isin(["Sales","HR"]))& (df["salary"]>70000)]
sale_hr_result2

  name   dept  salary    avg_salary  rank
0    A  Sales   90000  80000.000000   1.0
2    C     HR   80000  63333.333333   1.0